version: '3'
services:

  mysql:
    image: "mysql:5.7.39"
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}  
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TIME_ZONE}

