service: user
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  deleteUser:
    handler: src/function/deleteUser/handler.deleteOne
    events:
      - httpApi:
          path: /api/users/{id}
          method: put
  deleteByCron:
    handler: src/function/deleteUsersByCron/handler.deleteByTime
    events:
      - schedule:
          rate: cron(0 0 0 * * ?)
          enabled: true

