service: user
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - Fn::GetAtt: [ sqsQueue, Arn ]

resources:
  Resources:
    receiverQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqsQueue

functions:
  auth:
    handler: src/function/auth.authorize

  deleteUserByIp:
    handler: src/function/deleteUserByIp/handler.sender
    events:
      - http:
          method: post
          path: /api/users/{id}
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token

  deleteUsersByCron:
    handler: src/function/deleteUsersByCron/handler.sender
    events:
      - schedule:
          rate: cron(0 0 0 * * ?)
          enabled: true

  deleteUser:
    handler: src/function/deleteUser/handler.receiver
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - receiverQueue
              - Arn
